/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniFastSearch */

#ifndef _Included_JniFastSearch
#define _Included_JniFastSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniFastSearch
 * Method:    OnInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JniFastSearch_OnInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JniFastSearch
 * Method:    Query
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_JniFastSearch_Query
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     JniFastSearch
 * Method:    Run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniFastSearch_Run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
